[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "requests>=2.32.5",
    "streamlit>=1.53.0",
    "streamlit-autorefresh>=1.0.1",
]
